SOCIAL_AUTH_TWITTER_KEY = 'jnm77brvOZ0up6dSMWVDXBLTz'
SOCIAL_AUTH_TWITTER_SECRET = '2SfpaoT1HupFaDoMO6r8iHDkCDQ8fA3ShmQJkgihexWdqZuvsV'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
