"""
Django settings for social_auth project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y!^8hryflb__-dp2*p%9=ww+gaxsdol&vx47&8k#-g9$*+xe$t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']

SOCIAL_AUTH_TWITTER_KEY = 'jnm77brvOZ0up6dSMWVDXBLTz'

SOCIAL_AUTH_TWITTER_SECRET = '2SfpaoT1HupFaDoMO6r8iHDkCDQ8fA3ShmQJkgihexWdqZuvsV'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'social.apps.django_app.default',

    'social_auth_management',
)

SOCIAL_AUTH_LOGIN_ERROR_URL = '/'

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = "754zufsc3i0hay"

SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = "iU1gq1nnFecuUOR2"

SOCIAL_AUTH_FACEBOOK_KEY = "991267737603917"

SOCIAL_AUTH_FACEBOOK_SECRET = "99ac3c59d275a459b0e7d1f4e0e8ddf8"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "39094139190-ies6ie3me8c7qhk82qie6vcvm4t5gq9q.apps.googleusercontent.com"

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "CVN-mGkVJwmsVfHkmCtW2YgU"

SOCIAL_AUTH_GOOGLE_OAUTH_KEY = "39094139190-ies6ie3me8c7qhk82qie6vcvm4t5gq9q.apps.googleusercontent.com"

SOCIAL_AUTH_GOOGLE_OAUTH_SECRET = "CVN-mGkVJwmsVfHkmCtW2YgU"

SOCIAL_AUTH_GOOGLE_PLUS_KEY = "39094139190-ies6ie3me8c7qhk82qie6vcvm4t5gq9q.apps.googleusercontent.com"

SOCIAL_AUTH_GOOGLE_PLUS_SECRET = "CVN-mGkVJwmsVfHkmCtW2YgU"

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
)


AUTHENTICATION_BACKENDS = (
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.open_id.OpenIdAuth',
    'social.backends.google.GoogleOpenId',
    'social.backends.google.GoogleOAuth2',
    'social.backends.google.GoogleOAuth',
    'social.backends.twitter.TwitterOAuth',
    'social.backends.google.GooglePlusAuth',
    'social.backends.yahoo.YahooOpenId',
    'social.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


SOCIAL_AUTH_URL_NAMESPACE = 'social'


ROOT_URLCONF = 'social_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
